### ISSUE TITLE
E2E tests for Project Propose

### ISSUE THREAD

**Issue by ivelin** [SporosDAO/sweat-token#117]
- [x] Navigation in/out of pages
- [x] User input validation
  - [x] Required fields
  - [x] Manager ETH address
  - [x] Deadline
  - [x] Budget
  - [x] Chain
- [x] Error handling of on-chain read transactions

**Comment by ivelin** [comment]
test

**Comment by lipmaneth** [comment]
test

**Comment by ivelin** [comment]
Closing this issue as completed and opening a new one for contratWrite e2e tests. There is a blocking problem with synpress that needs to be resolved first.
https://github.com/Synthetixio/synpress/issues/472
