### ISSUE TITLE
E2E test Contract Write for Project Propose

### ISSUE THREAD

**Issue by ivelin** [SporosDAO/sweat-token#132]
-[ ] Write e2e test for Project Propose page contract write. 

Extending Issue https://github.com/SporosDAO/sweat-token/issues/117
Blocked on synpress issue https://github.com/Synthetixio/synpress/issues/472

**Comment by EdgeCaser** [comment]
MIlestone: Vfuture

**Comment by ivelin** [comment]
implemented in frontend testsuite via #153
