### ISSUE TITLE
Add Wallet Connect as login option

### ISSUE THREAD

**Issue by opny721** [SporosDAO/sweat-token#25]
Add Wallet Connect as a login  option, currently only Metamask is supported.

Documentation at https://docs.walletconnect.com/

**Comment by briareus-the-titan** [comment]
I think since we are using Rainbow's client this is working now right? @ivelin Can we close this?

**Comment by ivelin** [comment]
> I think since we are using Rainbow's client this is working now right? @ivelin Can we close this?

Yes, Rainbow kit offers WalletConnect as an option. Close this issue.
