### ISSUE TITLE
Remember Me feature

### ISSUE THREAD

**Issue by ivelin** [SporosDAO/sweat-token#45]
Mirror.xyz has a Remember Me feature that authorizes the app to ask the user to sign a message which then enables:
1. mirror to remember the signature in the browser local storage.
2. use the signature to publish new blog posts without asking the user to login with their wallet and sign each time.
3. Allow the user to return to the site multiple times without having to log into their crypto wallet each time.

This is a nice UX improvement because the interaction with wallets is still clunky and confusing often times.

A well designed message that restricts users to certain interactions such as browsing their DAO data and managing project tasks maybe an overall UX improvement without extra security risks.

For on-chain transactions that require gas payment or any kind of payment we would probably still want the user to verify explicitly and sign with their crypto wallet.

Mirror.xyz screenshots attached below:

<img width="471" alt="Screen Shot 2022-05-24 at 12 08 16 AM" src="https://user-images.githubusercontent.com/2234901/169954278-1d79d138-c0f6-429b-b456-45bc6c3d4ba1.png">
<img width="894" alt="Screen Shot 2022-05-24 at 12 09 49 AM" src="https://user-images.githubusercontent.com/2234901/169954281-801137b0-a6c4-4fb5-9700-ed4dca9fe96e.png">

**Comment by opny721** [comment]
Good suggestion, in #45 I address this via cookie to path in this initial phase. Will definitely look into this
