### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by opny721** [SporosDAO/sweat-token#8]
Setup CI/CD for automated testing and deployment

- [x] Netlify continuous deployment for `dev` and `main`(prod) branch
- [x] Heroku continous deployment for `dev` and `main` (prod) branch
- [x] Github action with:
  - [x] lint
  - [x] build
  - [x] test

**Comment by ivelin** [comment]
Mongodb Atlas account setup and linked to dev and prod CI/CD. Team account shared between @opny721 and @ivelin .

**Comment by opny721** [comment]
Seems all good here, shall we close? Thanks1

**Comment by ivelin** [comment]
I have a few more items on my list related to this issue:

- [ ] Github action with:
  - [ ] lint
  - [ ] build
  - [ ] test
- [ ] Condition netlify deployment on github action successful checks
- [ ] Condition heroku deployment on github action successful checks
